// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.28.0
// source: proto/dumbkv.proto

package dumbkv

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"` // интерпретируется как []byte
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutRequest) Reset() {
	*x = PutRequest{}
	mi := &file_proto_dumbkv_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutRequest) ProtoMessage() {}

func (x *PutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dumbkv_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutRequest.ProtoReflect.Descriptor instead.
func (*PutRequest) Descriptor() ([]byte, []int) {
	return file_proto_dumbkv_proto_rawDescGZIP(), []int{0}
}

func (x *PutRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *PutRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type PutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"` // optional: "ok", "error", etc.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutResponse) Reset() {
	*x = PutResponse{}
	mi := &file_proto_dumbkv_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutResponse) ProtoMessage() {}

func (x *PutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dumbkv_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutResponse.ProtoReflect.Descriptor instead.
func (*PutResponse) Descriptor() ([]byte, []int) {
	return file_proto_dumbkv_proto_rawDescGZIP(), []int{1}
}

func (x *PutResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_proto_dumbkv_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dumbkv_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_proto_dumbkv_proto_rawDescGZIP(), []int{2}
}

func (x *GetRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type GetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Found         bool                   `protobuf:"varint,2,opt,name=found,proto3" json:"found,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_proto_dumbkv_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dumbkv_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_proto_dumbkv_proto_rawDescGZIP(), []int{3}
}

func (x *GetResponse) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *GetResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_proto_dumbkv_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dumbkv_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_proto_dumbkv_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"` // optional
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_proto_dumbkv_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dumbkv_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_proto_dumbkv_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type SizeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SizeRequest) Reset() {
	*x = SizeRequest{}
	mi := &file_proto_dumbkv_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SizeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SizeRequest) ProtoMessage() {}

func (x *SizeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dumbkv_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SizeRequest.ProtoReflect.Descriptor instead.
func (*SizeRequest) Descriptor() ([]byte, []int) {
	return file_proto_dumbkv_proto_rawDescGZIP(), []int{6}
}

type SizeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Size          int32                  `protobuf:"varint,1,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SizeResponse) Reset() {
	*x = SizeResponse{}
	mi := &file_proto_dumbkv_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SizeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SizeResponse) ProtoMessage() {}

func (x *SizeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dumbkv_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SizeResponse.ProtoReflect.Descriptor instead.
func (*SizeResponse) Descriptor() ([]byte, []int) {
	return file_proto_dumbkv_proto_rawDescGZIP(), []int{7}
}

func (x *SizeResponse) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

var File_proto_dumbkv_proto protoreflect.FileDescriptor

const file_proto_dumbkv_proto_rawDesc = "" +
	"\n" +
	"\x12proto/dumbkv.proto\x12\x06dumbkv\"4\n" +
	"\n" +
	"PutRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"%\n" +
	"\vPutResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"\x1e\n" +
	"\n" +
	"GetRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"9\n" +
	"\vGetResponse\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\x12\x14\n" +
	"\x05found\x18\x02 \x01(\bR\x05found\"!\n" +
	"\rDeleteRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"(\n" +
	"\x0eDeleteResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"\r\n" +
	"\vSizeRequest\"\"\n" +
	"\fSizeResponse\x12\x12\n" +
	"\x04size\x18\x01 \x01(\x05R\x04size2\xdb\x01\n" +
	"\rDumbKVService\x12.\n" +
	"\x03Put\x12\x12.dumbkv.PutRequest\x1a\x13.dumbkv.PutResponse\x12.\n" +
	"\x03Get\x12\x12.dumbkv.GetRequest\x1a\x13.dumbkv.GetResponse\x127\n" +
	"\x06Delete\x12\x15.dumbkv.DeleteRequest\x1a\x16.dumbkv.DeleteResponse\x121\n" +
	"\x04Size\x12\x13.dumbkv.SizeRequest\x1a\x14.dumbkv.SizeResponseB\x19Z\x17pkg/proto/dumbkv;dumbkvb\x06proto3"

var (
	file_proto_dumbkv_proto_rawDescOnce sync.Once
	file_proto_dumbkv_proto_rawDescData []byte
)

func file_proto_dumbkv_proto_rawDescGZIP() []byte {
	file_proto_dumbkv_proto_rawDescOnce.Do(func() {
		file_proto_dumbkv_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_dumbkv_proto_rawDesc), len(file_proto_dumbkv_proto_rawDesc)))
	})
	return file_proto_dumbkv_proto_rawDescData
}

var file_proto_dumbkv_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_dumbkv_proto_goTypes = []any{
	(*PutRequest)(nil),     // 0: dumbkv.PutRequest
	(*PutResponse)(nil),    // 1: dumbkv.PutResponse
	(*GetRequest)(nil),     // 2: dumbkv.GetRequest
	(*GetResponse)(nil),    // 3: dumbkv.GetResponse
	(*DeleteRequest)(nil),  // 4: dumbkv.DeleteRequest
	(*DeleteResponse)(nil), // 5: dumbkv.DeleteResponse
	(*SizeRequest)(nil),    // 6: dumbkv.SizeRequest
	(*SizeResponse)(nil),   // 7: dumbkv.SizeResponse
}
var file_proto_dumbkv_proto_depIdxs = []int32{
	0, // 0: dumbkv.DumbKVService.Put:input_type -> dumbkv.PutRequest
	2, // 1: dumbkv.DumbKVService.Get:input_type -> dumbkv.GetRequest
	4, // 2: dumbkv.DumbKVService.Delete:input_type -> dumbkv.DeleteRequest
	6, // 3: dumbkv.DumbKVService.Size:input_type -> dumbkv.SizeRequest
	1, // 4: dumbkv.DumbKVService.Put:output_type -> dumbkv.PutResponse
	3, // 5: dumbkv.DumbKVService.Get:output_type -> dumbkv.GetResponse
	5, // 6: dumbkv.DumbKVService.Delete:output_type -> dumbkv.DeleteResponse
	7, // 7: dumbkv.DumbKVService.Size:output_type -> dumbkv.SizeResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_dumbkv_proto_init() }
func file_proto_dumbkv_proto_init() {
	if File_proto_dumbkv_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_dumbkv_proto_rawDesc), len(file_proto_dumbkv_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_dumbkv_proto_goTypes,
		DependencyIndexes: file_proto_dumbkv_proto_depIdxs,
		MessageInfos:      file_proto_dumbkv_proto_msgTypes,
	}.Build()
	File_proto_dumbkv_proto = out.File
	file_proto_dumbkv_proto_goTypes = nil
	file_proto_dumbkv_proto_depIdxs = nil
}
